# Snapfile for PaceMark automated screenshots
# This file will be used by fastlane snapshot to take screenshots

# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro Max"
])

# A list of languages that should be used
languages([
  "fr-FR",
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("trailmark")

# Should the project be cleaned before building it?
clean(false)

# Reuse Xcode's build cache for faster runs
derived_data_path("~/Library/Developer/Xcode/DerivedData")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")
# Note: after merge, screenshots land in trailmark/screenshots/
# The landing page accesses them via symlink: pacemark-landingpage/screenshots-app → ../trailmark/screenshots

# Remove the '#' and change the propertie names if you need any other localization than the default.
# number_of_retries(3)

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Optional: Remove the '#' and set custom XCARGS for the build phase
# xcargs("-skipPackagePluginValidation -skipMacroValidation")

# Note: SlowMo is disabled by default in snapshot

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-AppleLanguages (en-US)", "-AppleLocale en_US"])

# For more information about all available options run
# fastlane action snapshot